### ISSUE TITLE
[ЗАПРОС] Исправить файл лицензии

### ISSUE THREAD

**Issue by MarcoRavich** [ALFiX01/AssistantX#4]
**[Google-RU]**
Привет, прежде всего спасибо за эту потрясающую работу!

Поскольку я «доксировал» ее на [странице TWEAKERS](https://github.com/MarcoRavich/Opendows/blob/main/Tweakers.md#-) [проекта Opendows](https://forart.it/opendows), не могли бы вы исправить (файл лицензии, совместимый с GH) для нее?

«Проблема» в том, что соответствующий значок лицензии генерируется неправильно, как вы можете видеть:

![](https://flat.badgen.net/github/license/ALFiX01/ASX-Hub)
(URL-адрес генератора: https://flat.badgen.net/github/license/ALFiX01/ASX-Hub)

Где он должен быть быть:
![](https://flat.badgen.net/github/license/all-licenses/GNU-Affero-General-Public-License-v3.0)
(URL-адрес генератора: https://flat.badgen.net/github/license/all-licenses/GNU-Affero-General-Public-License-v3.0)

Это должно быть легко исправлено выбором «правильного» файла лицензии с помощью мастера GH.

И последнее, но не менее важное: я приглашаю вас присоединиться к [обсуждениям CS](https://github.com/mewostick/Creosynth/discussions), чтобы делиться идеями о настройках Windows.

Заранее спасибо!

**[ENG]**
Hi there, 1st of all thanks for this awesome work !

Since I've 'doxed' it in the [TWEAKERS page](https://github.com/MarcoRavich/Opendows/blob/main/Tweakers.md#-) of the [Opendows project](https://forart.it/opendows), can you please fix (GH-compliant license file for it ?

The "problem" is that the relative license badge isn't generated correctly, as you can see:

![](https://flat.badgen.net/github/license/ALFiX01/ASX-Hub)
(generator URL: https://flat.badgen.net/github/license/ALFiX01/ASX-Hub)

Where it should be:
![](https://flat.badgen.net/github/license/all-licenses/GNU-Affero-General-Public-License-v3.0)
(generator URL: https://flat.badgen.net/github/license/all-licenses/GNU-Affero-General-Public-License-v3.0)

This should be easily fixed by choosing a "correct" license file through the GH's wizard.

Last but not least, I invite you to join [CS Discussions](https://github.com/mewostick/Creosynth/discussions) to share ideas about Windows tweakings.

Thanks in advance !

**Comment by ALFiX01** [comment]
Thanks for adding my project. I fixed what you said)

**Comment by MarcoRavich** [comment]
Works now, thanks !!

Hope you'll join [CS Discussions](https://github.com/mewostick/Creosynth/discussions) to share ideas, knowledge and more about Windows tweaks.
